### PR TITLE
[ui-kit] Login portal icons + background

### LINKED ISSUE #69: [ui-kit] Login portal icons + background
Blocking kaching login portal

- [x]  Add icons for all providers
- [x]  Allow LoginPortal to have transparent background

### PR DESCRIPTION
**Pull request by alekseevaiana**
Closes #69

### CODE REVIEW

**Comment by alekseevaiana** [comment]
## Issue 1
When test package with `"@usekeyp/ui-kit": "file:../../keyp/usekeyp-js-sdk/packages/ui-kit"` in package.json
In UserAccount.js file it tries to import helpers.jsx. Screenshot below.
Resolved by changing helpers.jsx into helpers.js.

Screenshot 2023-06-28 at 4 36 55 PM

**Comment by alekseevaiana** [comment]
## Issue 2
Link with documentation mentioned in error message: https://nextjs.org/docs/messages/react-hydration-error.
Comment: thought that I resolved it by running `yarn build`, error was gone, but then appeared again.

Screenshot 2023-06-28 at 5 06 06 PM

Screenshot 2023-06-28 at 4 42 42 PM

Screenshot 2023-06-28 at 4 45 40 PM

Screenshot 2023-06-28 at 4 48 30 PM


Screenshot 2023-06-28 at 4 45 59 PM

Screenshot 2023-06-28 at 4 46 10 PM

**Comment by alekseevaiana** [comment]
## Issue 3
Don't see twitch icon. Maybe because of Issue 2

**Comment by alekseevaiana** [comment]
Made LoginFrame with transparent background variant and align center.

Screenshot 2023-07-03 at 9 00 00 AM

**Review by pi0neerpat — APPROVED** [review]

**Comment by alekseevaiana** [comment]
@pi0neerpat I tested login with REDDIT and CHESS providers, it works as well. So you can publish. 

Screenshot 2023-07-05 at 11 22 02 AM

**Pull request merged**
